# This action compiles the library and runs all unit tests using an OS and CMake matrix
name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# Define the matrix for different operating systems
jobs:
  build-and-test:
    name: ${{ matrix.os }} / CMake ${{ matrix.cmakeVersion }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Windows-2019 is used as a dedicated 32-bit build/test platform
        os: [ubuntu-latest, macos-latest, windows-latest, windows-2019]
        # CMake >= 3.21 is required to use "--preset <presetName>" and discover generators
        cmakeVersion: ["3.21", latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone required submodules
      run: |
        git submodule init extern/googletest
        git submodule update

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: ${{ matrix.cmakeVersion }}

    - name: "CMake: Build and Test (32-bit)"
      if: matrix.os == 'windows-2019'
      uses: lukka/run-cmake@v10
      with:
        configurePreset: release32
        configurePresetAdditionalArgs: "['-DBUILD_DOCS=OFF']"
        buildPreset: release32
        testPreset: release32

    - name: "CMake: Build and Test (64-bit)"
      if: matrix.os != 'windows-2019'
      uses: lukka/run-cmake@v10
      with:
        configurePreset: release64
        configurePresetAdditionalArgs: "['-DBUILD_DOCS=OFF']"
        buildPreset: release64
        testPreset: release64
